name: Update Repo
on:
  workflow_dispatch:
    inputs:
      download_url:
        description: 'URL to download the zip file from'
        required: true
        default: ''
jobs:
  update-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Pull latest changes
        run: git pull origin main
      - name: Download zip file
        run: |
          # Use the required input parameter for download URL
          DOWNLOAD_URL="${{ github.event.inputs.download_url }}"
          curl -L -o espresso-main.zip "$DOWNLOAD_URL"
          unzip espresso-main.zip -d espresso
          rm -rf WB
          mv espresso/espresso-main/* .
      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add WB/*
          git commit -m "Initial commit"
          git push